//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> AccommodationID { get; set; }
        public Nullable<int> AccommodationReview { get; set; }
        public Nullable<int> DestinationReview { get; set; }
        public string AdditionalComments { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual DestinationMst DestinationMst { get; set; }
        public virtual UserMst UserMst { get; set; }
    }
}
