//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidesMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuidesMst()
        {
            this.Images = new HashSet<Image>();
            this.TransactionMsts = new HashSet<TransactionMst>();
        }
    
        public int GuideID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Fees { get; set; }
    
        public virtual DestinationMst DestinationMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionMst> TransactionMsts { get; set; }
    }
}
