//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionMst
    {
        public int TransactionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> GuideID { get; set; }
        public string CardNumber { get; set; }
        public string Status { get; set; }
    
        public virtual CardDetail CardDetail { get; set; }
        public virtual DestinationMst DestinationMst { get; set; }
        public virtual GuidesMst GuidesMst { get; set; }
        public virtual UserMst UserMst { get; set; }
    }
}
